export const GET_BALANCE_SUCCESS = "GET_BALANCE_SUCCESS_STACKBLITZ"
export const GET_BALANCE_ERROR = "GET_BALANCE_ERROR_STACKBLITZ"
export const REMOVE_GET_BALANCE_ERROR = "REMOVE_GET_BALANCE_ERROR_STACKBLITZ"